services:
  app:
    container_name: "passportvision-app"
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:15-alpine
    container_name: "passportvision-db"
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db-data:
    driver: local
